repos:
- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v4.2.0
  hooks:
    - id: check-merge-conflict
    - id: trailing-whitespace
- repo: https://github.com/sirosen/check-jsonschema
  rev: 0.14.3
  hooks:
    - id: check-github-workflows
    - id: check-readthedocs
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
    - id: black
      name: "Autoformat python files"
- repo: https://github.com/asottile/blacken-docs
  rev: v1.12.1
  hooks:
    - id: blacken-docs
      additional_dependencies: ['black==21.12b0']
- repo: https://github.com/PyCQA/flake8
  rev: 4.0.1
  hooks:
    - id: flake8
      name: "Lint python files"
      additional_dependencies: ['flake8-bugbear==21.11.29']
- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
    - id: isort
      name: "Sort python imports"
- repo: https://github.com/asottile/pyupgrade
  rev: v2.32.0
  hooks:
    - id: pyupgrade
      args: ["--py36-plus"]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.950
  hooks:
    - id: mypy
      files: ^src/globus_sdk/
      additional_dependencies:
        - types-docutils
        - types-jwt
        - types-requests
        - responses  # signatures for code in `_testing`
