repos:
- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v4.4.0
  hooks:
    - id: check-merge-conflict
    - id: trailing-whitespace
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.23.3
  hooks:
    - id: check-github-workflows
    - id: check-readthedocs
- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
    - id: black
      name: "Autoformat python files"
- repo: https://github.com/asottile/blacken-docs
  rev: 1.15.0
  hooks:
    - id: blacken-docs
      additional_dependencies: ['black==23.7.0']
- repo: https://github.com/PyCQA/flake8
  rev: 6.1.0
  hooks:
    - id: flake8
      name: "Lint python files"
      additional_dependencies:
        - 'flake8-bugbear==23.7.10'
        - 'flake8-comprehensions==3.14.0'
        - 'flake8-typing-as-t==0.0.3'
- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
    - id: isort
      name: "Sort python imports"
- repo: https://github.com/asottile/pyupgrade
  rev: v3.10.1
  hooks:
    - id: pyupgrade
      args: ["--py37-plus"]
- repo: https://github.com/codespell-project/codespell
  rev: v2.2.5
  hooks:
    - id: codespell
      args: ["--ignore-regex", "https://[^\\s]*"]

# custom local hooks
- repo: local
  hooks:
    - id: generate-init
      name: "Check generated __init__.py"
      entry: ./src/globus_sdk/_generate_init.py
      language: python
      always_run: true
      pass_filenames: false
    - id: forbid-code-block-without-language
      name: Require code-block directives to specify a language
      types_or: [python,rst]
      language: pygrep
      entry: "\\.\\. +code-block::$"
