sudo: false
dist: xenial
language: python
matrix:
  include:
    - python: "2.7"
      env: TOXENV=py
    # test on 3.5...3.8
    - python: "3.5"
      env: TOXENV=py
    - python: "3.6"
      env: TOXENV=py
    # use py3.6 for linting build to support black, isort
    - name: "lint (python: 3.6)"
      python: "3.6"
      env: TOXENV=lint
    - name: "docs (python: 3.6)"
      python: "3.6"
      env: TOXENV=docs
    - python: "3.7"
      env: TOXENV=py
    - python: "3.8"
      env: TOXENV=py
    - python: "pypy"
      env: TOXENV=py
    # non-Linux testing
    #   https://docs.travis-ci.com/user/languages/python/#running-python-tests-on-multiple-operating-systems
    #
    # Windows
    - name: "py2 + windows"
      os: windows
      language: shell
      env: TOXENV=py PATH=/c/Python27:/c/Python27/Scripts:$PATH
      before_install:
        - choco install python2
        - python -m pip install --upgrade pip wheel
    - name: "py3.8 + windows"
      os: windows
      language: shell
      env: TOXENV=py PATH=/c/Python38:/c/Python38/Scripts:$PATH
      before_install:
        - choco install python3
        - python -m pip install --upgrade pip wheel
    # macOS
    - name: "py2 + macOS"
      os: osx
      osx_image: xcode10.2  # py3.7 on macOS 10.14, but we will use py2
      language: shell
      env: TOXENV=py2
    - name: "py3 + macOS"
      os: osx
      osx_image: xcode10.2  # py3.7 on macOS 10.14
      language: shell
      env: TOXENV=py3

  allow_failures:
    - python: "pypy"
cache: pip
install:
  - pip install -e '.[development]'
script:
  - tox
