name: build
on:
  push:
  pull_request:
  # build weekly at 4:00 AM UTC
  schedule:
    - cron: '0 4 * * 1'

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: python -m pip install -U tox
      - run: tox -e pylint

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: python -m pip install -U tox
      - run: tox -e mypy,mypy-test

  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        # we do not want a large number of windows and macos builds, so
        # enumerate them explicitly
        include:
          - os: windows-latest
            python-version: "3.11"
          - os: macos-latest
            python-version: "3.11"
    name: "test py${{ matrix.python-version }} on ${{ matrix.os }} "
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: install tox
        run: python -m pip install -U tox
      - name: run tests
        run: python -m tox -e py,coverage_report

  test-lazy-imports:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: python -m pip install -U tox
      - run: tox -e test-lazy-imports

  test-mindeps:
    runs-on: ubuntu-latest
    name: "mindeps"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - name: install tox
        run: python -m pip install -U tox
      - name: test
        run: tox -e py-mindeps

  test-package-metadata:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: install tox
        run: python -m pip install -U tox
      - name: check package metadata
        run: python -m tox -e twine-check,poetry-check
